### ISSUE TITLE
Accept a local file

### ISSUE THREAD

**Issue by ricobl** [tsuru/rpaas#3]
It would be nice to pass a local file to the `content` argument as it may contain multiline content.

**Comment by fsouza** [comment]
We've implemented that and I forgot to close the issue, sorry about that x)

Users are now able to provide files to -c by using @ + the name of the file. Example:

```
% tsuru rpaas route add -s rpaas -i myinstance -p / -c @my_location
```

Where "my_location" is a name of the file containing the location.

**Comment by ricobl** [comment]
Great! Thanks @fsouza!
